services:
    aylien:
        class: AYLIEN\TextAPI
        arguments: ['%aylien_id%', '%aylien_key%']

    hydrator:
        class: AppBundle\Service\Hydrator

    beer.info:
        class: AppBundle\Service\BeerInfo
        arguments: ['@hydrator', '@aylien']

    output.twig.extension:
        class: AppBundle\Twig\OutputExtension
        tags:
            - { name: twig.extension }

    build.sitemap:
        class: AppBundle\Command\BuildSitemapCommand
        arguments: ['@beer.info']
        tags:
            - { name: console.command }